### ISSUE TITLE
Installation in Symfony?

### ISSUE THREAD

**Issue by ThomasLandauer** [alisqi/TwigQI#3]
How can this extension be enabled in Symfony? At https://github.com/alisqi/TwigQI?tab=readme-ov-file#usage you're saying:
```php
$twig->addExtension(new AlisQI\TwigQI\Extension());
```
But I don't think I have that. According to https://symfony.com/doc/current/reference/dic_tags.html#twig-extension it should be enabled automatically?

How can I verify that this is running? In which files are those `E_USER_*` errors logged by default?

**Comment by zmitic** [comment]
Because it is a package and not a bundle, you need this in your `services.yaml`:

```yaml
when@dev:
    services:
        AlisQI\TwigQI\Extension:
            tags: [ 'twig.extension' ]
```
